services:
  apiapp:
    build:
      context: ./api/
    networks:
     - bridge
    ports:
      - 3000:3001

  dashboardapp:
    build:
      context: ./dashboard/
    networks:
     - bridge
    ports:
      - 80:80

networks:
  redConexion:
    driver: bridge